// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TgBackupSearch.Model;

#nullable disable

namespace TgBackupSearch.Migrations
{
    [DbContext(typeof(ChannelContext))]
    [Migration("20260118235012_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("TgBackupSearch.Model.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("DT")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("TelegramId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("DirPath")
                        .IsUnique();

                    b.ToTable("Item");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TgBackupSearch.Model.Media", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("DT")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TelegramId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaId");

                    b.HasIndex("ItemId");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("TgBackupSearch.Model.MetadataCache", b =>
                {
                    b.Property<int>("FileCacheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastWriteDT")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("FileCacheId");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Cache");
                });

            modelBuilder.Entity("TgBackupSearch.Model.Recognition", b =>
                {
                    b.Property<int>("RecognitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("RecognitionId");

                    b.HasIndex("MediaId");

                    b.ToTable("Recognitions");
                });

            modelBuilder.Entity("TgBackupSearch.Model.Comment", b =>
                {
                    b.HasBaseType("TgBackupSearch.Model.Item");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("PostId");

                    b.HasDiscriminator().HasValue("Comment");
                });

            modelBuilder.Entity("TgBackupSearch.Model.Post", b =>
                {
                    b.HasBaseType("TgBackupSearch.Model.Item");

                    b.HasDiscriminator().HasValue("Post");
                });

            modelBuilder.Entity("TgBackupSearch.Model.Media", b =>
                {
                    b.HasOne("TgBackupSearch.Model.Item", "Item")
                        .WithMany("Media")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("TgBackupSearch.Model.Recognition", b =>
                {
                    b.HasOne("TgBackupSearch.Model.Media", "Media")
                        .WithMany("Recognitions")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("TgBackupSearch.Model.Comment", b =>
                {
                    b.HasOne("TgBackupSearch.Model.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("TgBackupSearch.Model.Item", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("TgBackupSearch.Model.Media", b =>
                {
                    b.Navigation("Recognitions");
                });

            modelBuilder.Entity("TgBackupSearch.Model.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
